name: Tag
version: '1.0'
main: me.vinzoperez.core.Tag
api-version: '1.21.4'
commands:

  tag:
    description: "Tag Minigame"
    usage: "/Tag [help]"
permissions:
  core.command.explodeEntity:
    default: op
  core.command.use:
    default: op